<?php

/**
 * @file
 * It allows users to mark individual nodes as private.
 * Users authenticated with CAS can
 * read these nodes, while others cannot.
 */

define('PRIVATE_CAS_DISABLED', 0);
define('PRIVATE_CAS_ALLOWED', 1);
define('PRIVATE_CAS_AUTOMATIC', 2);
define('PRIVATE_CAS_ALWAYS', 3);
define('PRIVATE_CAS_GRANT_ALL', 1);


/**
 * Implements hook_permission().
 */
function private_cas_permission() {
  return array(
    'mark content as private' => array(
      'title' => t('Mark content as private'),
      'description' => t('Make content only viewable by people authenticated with cas'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function private_cas_menu() {
  $items = array();

  $items['admin/config/people/private_cas'] = array(
    'title' => 'Private (CAS)',
    'description' => "",
    'access arguments' => array('administer site'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('private_cas_general_settings'),
    'file' => 'private_cas.admin.inc',
    'file path' => drupal_get_path('module', 'private_cas'),
  );
  return $items;
}

/**
 * Implements hook_form_alter().
 *
 * This module adds a simple checkbox to the node form labeled private. If the
 * checkbox is labelled, only the node author and users authenticated with CAS
 * may see it.
 */
function private_cas_form_alter(&$form, &$form_state, $form_id) {
  if (!empty($form['#node_edit_form'])) {
    $node = $form['#node'];
    $default = variable_get('private_cas_' . $node->type, PRIVATE_CAS_DISABLED);

    if ($default != PRIVATE_CAS_DISABLED || !empty($node->private_cas)) {
      if (empty($node->nid)) {
        $privacy = ($default > PRIVATE_CAS_ALLOWED);
      }
      else {
        $privacy = isset($node->private_cas) ? $node->private_cas : 0;
      }

      if (user_access('mark content as private') && $default != PRIVATE_CAS_ALWAYS) {
        $form['options']['private_cas'] = array(
          '#type' => 'checkbox',
          '#title' => t('Make this post private'),
          '#attributes' => array('title' => t('When checked, only users authenticated with CAS will be able to see this post.')),
          '#default_value' => $privacy,
        );
      }
      else {
        $form['private_cas'] = array(
          '#type' => 'value',
          '#value' => $privacy,
        );
      }
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function private_cas_form_node_type_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['type'])) {
    $form['workflow']['private_cas'] = array(
      '#type' => 'radios',
      '#title' => t('Privacy (CAS)'),
      '#options' => array(
        PRIVATE_CAS_DISABLED => t('Disabled (always public)'),
        PRIVATE_CAS_ALLOWED => t('Enabled (public by default)'),
        PRIVATE_CAS_AUTOMATIC => t('Enabled (private by default)'),
        PRIVATE_CAS_ALWAYS => t('Hidden (always private)'),
      ),
      '#default_value' => variable_get('private_cas_' . $form['#node_type']->type, PRIVATE_CAS_DISABLED),
    );
  }
}

/**
 * Implements hook_node_load().
 */
function private_cas_node_load($nodes, $types) {
  $result = db_query('SELECT * FROM {private_cas} WHERE nid IN(:nids)', array(':nids' => array_keys($nodes)));
  foreach ($result as $record) {
    $nodes[$record->nid]->private_cas = $record->private_cas;
  }
}

/**
 * Implements hook_node_delete().
 */
function private_cas_node_delete($node) {
  db_delete('private_cas')
    ->condition('nid', $node->nid)
    ->execute();
}

/**
 * Implements hook_node_insert().
 */
function private_cas_node_insert($node) {
  private_cas_node_update($node);
}

/**
 * Implements hook_node_update().
 */
function private_cas_node_update($node) {
  if (isset($node->private_cas)) {
    db_merge('private_cas')
      ->key(array('nid' => $node->nid))
      ->fields(array(
        'nid' => $node->nid,
        'private_cas' => (int)$node->private_cas,
      ))
      ->execute();

    $vars = array(
      '@type' => node_type_get_name($node),
      '%title' => $node->title,
      '%private' => !empty($node->private_cas) ? t('Yes') : t('No'),
    );
    drupal_set_message(t('@type %title has private set to "%private".', $vars));
  }
}

/**
 * Implements hook_node_view().
 */
function private_cas_node_view($node, $view_mode) {
  if (isset($node->private_cas) && $node->private_cas == 1) {
    $links['private_cas_icon']['title'] = theme('private_cas_node_link');
    $links['private_cas_icon']['html'] = TRUE;
    $node->content['links']['private_cas'] = array(
      '#theme' => 'links__node__private_cas',
      '#links' => $links,
      '#attributes' => array('class' => array('links', 'inline')),
    );
  }
}

/**
 * Implements hook_theme().
 */
function private_cas_theme() {
  return array(
    'private_cas_node_link' => array(
      'variables' => array(),
    ),
  );
}

/**
 * Custom theme function
 * @see private_cas_theme()
 */
function theme_private_cas_node_link() {
  $vars = array(
    'path' => drupal_get_path('module', 'private_cas') . '/icon_key.gif',
    'width' => '16',
    'height' => '16',
    'alt' => t('Private CAS'),
    'title' => t('This content is private.')
  );
  return theme('image', $vars);
}




